# ------------------------------------------
# ---------------- POSTS ----------------
# ------------------------------------------

### Obter postagens
GET http://localhost:3001/posts

### Obter postagem por id
GET http://localhost:3001/posts/3

### Buscar postagens por palavra-chave
GET http://localhost:3001/posts/search?keyword=Conteúdo

### Inserir um novo post
POST http://localhost:3001/posts
Content-Type: application/json

{
  "titulo": "Novo Post",
  "subtitulo": "Subtítulo do Novo Post",
  "conteudo": "Este é o conteúdo do novo post.",
  "urlimagem": null,
  "idusuario": 3
}

### Atualizar post
PUT http://localhost:3001/posts/9
Content-Type: application/json

{
    "titulo": "Alterando o título",
    "subtitulo": "Alterando Subtítulo",
    "conteudo": "Conteúdo do Post",
    "urlimagem": null,
    "dtcriacao": "2024-12-27T03:02:12.450Z",
    "dtalteracao": "2024-12-27T03:02:12.450Z",
    "usuario": 5,
    "usuarioAlteracao": 6
}

### Excluir post
DELETE http://localhost:3001/posts/4





# ------------------------------------------
# ---------------- USUÁRIOS ----------------
# ------------------------------------------

### Listar todos os usuários
GET http://localhost:3001/users

### Buscar um usuário por ID
GET http://localhost:3001/users/1

### Criar um novo usuário
POST http://localhost:3001/users
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "email@gmail.com",
  "role": "Aluno",
  "ativo": true
}

### Atualizar um usuário existente
PUT http://localhost:3001/users/1
Content-Type: application/json

{
  "nome": "João Atualizado"
}

### Excluir um usuário
DELETE http://localhost:3001/users/1
